config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :products do
    get :who_bought, on: :member
  end
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
  resources :line_items do
   put 'decrement', on: :member
   put 'increase', on: :member
  end

end

app/views/layouts/application.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<%= I18n.locale || 'en' %>" lang="<%= I18n.locale || 'en'%>">
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= form_tag store_path, class: "locale" do %>
      <%= select_tag "set_locale",
      options_for_select(LANGUAGES, I18n.locale.to_s),
      onchange: 'this.form.submit()'  %>
      <%= submit_tag "submit" %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("logo.png") %>
    <%=  @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %>
      <% end %>
      <% end %>
      <ul>
        <li><%= link_to t('.home'), store_path %></li>
        <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
        <li><a href="http://www..../news"><%= t('.news') %></a></li>
        <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
      </ul>
      <% if session[:user_id] %>
          <ul>
            <li><%= link_to "Order", orders_path %></li>
            <li><%= link_to "Products", products_path, class: "btn btn-primary" %></li>
            <li><%= link_to "Users", users_path, class: "btn btn-primary" %></li>
          </ul>
          <%= button_to "Logout", logout_path,  method: :delete, class: "btn btn-primary" %>
      <% end %>
      <p><%=  l @date_loaded, :format => :short %></p>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>